/* 
    States for CRUD
*/
export const SEARCHING = "SEARCHING"
export const INSERTING = "INSERTING"
export const EDITING   = "EDITING"

/*
    States para FICHA
*/
export const STATE_CADASTRO          = "STATE_CADASTRO"
export const STATE_CUSTODIADOS       = "STATE_CUSTODIADOS"
export const STATE_BLACKLIST         = "STATE_BLACKLIST"
export const STATE_BLOQUEIOS         = "STATE_BLOQUEIOS"
export const STATE_VISITA            = "STATE_VISITA"
export const STATE_ADVOGADO          = "STATE_ADVOGADO"
export const STATE_BIOMETRIA         = "STATE_BIOMETRIA"
export const STATE_COMPANHEIROS_CELA = "STATE_COMPANHEIROS_CELA"
export const STATE_MOVIMENTACOES     = "STATE_MOVIMENTACOES"
export const STATE_HISTORICO_VISITAS = "STATE_HISTORICO_VISITAS"
export const STATE_PROCESSOS         = "STATE_PROCESSOS"
export const STATE_SAUDE             = "STATE_SAUDE"

/*
    States para RELATÓRIO
*/

export const STATE_SINTETICO = "STATE_SINTETICO"
export const STATE_ANALITICO = "STATE_ANALITICO"

/*
    States para TELA DE RELATÓRIO GERAL DE ESTATÍSTICAS
*/

export const STATE_RELATORIO_POPULACAO_CARCERARIA = "STATE_RELATORIO_POPULACAO_CARCERARIA"
export const STATE_RELATORIO_POPULACAO_CARCERARIA_RESUMO = "STATE_RELATORIO_POPULACAO_CARCERARIA_RESUMO"
export const STATE_RELATORIO_BIOMETRIA = "STATE_RELATORIO_BIOMETRIA"
export const STATE_RELATORIO_DEPEN_CRIME = "STATE_RELATORIO_DEPEN_CRIME"
export const STATE_RELATORIO_SAUDE_ATENDIMENTO_MEDICO = "STATE_RELATORIO_SAUDE_ATENDIMENTO_MEDICO"
export const STATE_RELATORIO_SAUDE_MEDICAMENTO = "STATE_RELATORIO_SAUDE_MEDICAMENTO"
export const STATE_RELATORIO_SAUDE_PATOLOGIA = "STATE_RELATORIO_SAUDE_PATOLOGIA"
export const STATE_RELATORIO_SAUDE_VACINA = "STATE_RELATORIO_SAUDE_VACINA"

/*
    States para TELA GERAL DE CRUD DE TABELAS DOMÍNIO
*/

export const STATE_CRUD_SAUDE_VACINA = "STATE_CRUD_SAUDE_VACINA"
export const STATE_CRUD_SAUDE_MEDICAMENTO = "STATE_CRUD_SAUDE_MEDICAMENTO"
export const STATE_CRUD_SAUDE_PATOLOGIA = "STATE_CRUD_SAUDE_PATOLOGIA"
export const STATE_CRUD_SAUDE_ESPECIALIDADE_MEDICA = "STATE_CRUD_SAUDE_ESPECIALIDADE_MEDICA"