/* 
    States for CRUD
*/
export const SEARCHING = "SEARCHING"
export const INSERTING = "INSERTING"
export const EDITING   = "EDITING"
export const VIEWING   = "VIEWING"

/*
    States para FICHA
*/
export const STATE_CADASTRO          = "STATE_CADASTRO"
export const STATE_CUSTODIADOS       = "STATE_CUSTODIADOS"
export const STATE_BLACKLIST         = "STATE_BLACKLIST"
export const STATE_BLOQUEIOS         = "STATE_BLOQUEIOS"
export const STATE_VISITA            = "STATE_VISITA"
export const STATE_ADVOGADO          = "STATE_ADVOGADO"
export const STATE_BIOMETRIA         = "STATE_BIOMETRIA"
export const STATE_COMPANHEIROS_CELA = "STATE_COMPANHEIROS_CELA"
export const STATE_MOVIMENTACOES     = "STATE_MOVIMENTACOES"
export const STATE_HISTORICO_VISITAS = "STATE_HISTORICO_VISITAS"
export const STATE_PROCESSOS         = "STATE_PROCESSOS"
export const STATE_SAUDE             = "STATE_SAUDE"

/*
    States para RELATÓRIO
*/

export const STATE_SINTETICO = "STATE_SINTETICO"
export const STATE_ANALITICO = "STATE_ANALITICO"

/*
    States para TELA DE RELATÓRIO GERAL DE ESTATÍSTICAS
*/

export const STATE_RELATORIO_CONTAS_A_PAGAR = "STATE_RELATORIO_CONTAS_A_PAGAR"
export const STATE_RELATORIO_CONTAS_A_RECEBER = "STATE_RELATORIO_CONTAS_A_RECEBER"
export const STATE_RELATORIO_CONTAS_PAGAS = "STATE_RELATORIO_CONTAS_PAGAS"
export const STATE_RELATORIO_CONTAS_RECEBIDAS = "STATE_RELATORIO_CONTAS_RECEBIDAS"
export const STATE_RELATORIO_RESUMO_MENSAL = "STATE_RELATORIO_RESUMO_MENSAL"
export const STATE_RELATORIO_LISTAGEM_VENDA = "STATE_RELATORIO_LISTAGEM_VENDA"

/*
    States para TELA GERAL DE CRUD DE TABELAS DOMÍNIO
*/

export const STATE_CRUD_SAUDE_VACINA = "STATE_CRUD_SAUDE_VACINA"
export const STATE_CRUD_SAUDE_MEDICAMENTO = "STATE_CRUD_SAUDE_MEDICAMENTO"
export const STATE_CRUD_SAUDE_PATOLOGIA = "STATE_CRUD_SAUDE_PATOLOGIA"
export const STATE_CRUD_SAUDE_ESPECIALIDADE_MEDICA = "STATE_CRUD_SAUDE_ESPECIALIDADE_MEDICA"